# Generated by Django 3.2.5 on 2021-07-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_create_currency_and_exchange_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyexchangerate',
            options={'ordering': ('-valuation_date', 'source_currency'), 'verbose_name': 'currency exchange rate', 'verbose_name_plural': 'currency exchange rates'},
        ),
    ]
